# Generated by Django 3.1.2 on 2020-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_client_deals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.ManyToManyField(to='deals.Deals')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='gems',
            field=models.ManyToManyField(to='deals.Gems'),
        ),
    ]
