# Generated by Django 3.1.2 on 2020-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20201009_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='gem',
            field=models.ManyToManyField(to='deals.Gems'),
        ),
    ]
