# Generated by Django 3.1.2 on 2020-10-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_deals_spend_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='spend_money',
        ),
        migrations.RemoveField(
            model_name='gems',
            name='users',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='gem',
        ),
        migrations.AddField(
            model_name='deals',
            name='gem',
            field=models.ManyToManyField(related_name='gems', to='deals.Gems'),
        ),
        migrations.AlterField(
            model_name='gems',
            name='gem_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
