# Generated by Django 3.1.2 on 2020-10-09 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_remove_deals_gem'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='gem',
            field=models.ManyToManyField(to='deals.Gems'),
        ),
    ]
