# Generated by Django 3.1.2 on 2020-10-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_deals_gem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='gem',
            field=models.ManyToManyField(related_name='gems', to='deals.Gems'),
        ),
    ]
