# Generated by Django 3.1.2 on 2020-10-09 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_auto_20201009_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='gem',
        ),
        migrations.AddField(
            model_name='deals',
            name='gem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='gems', to='deals.gems'),
            preserve_default=False,
        ),
    ]
