# Generated by Django 3.1.2 on 2020-10-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_auto_20201009_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.AddField(
            model_name='gems',
            name='deals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='deals.deals'),
            preserve_default=False,
        ),
    ]
