# Generated by Django 3.1.2 on 2020-10-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0016_auto_20201010_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gems',
            name='deals',
        ),
    ]
