# Generated by Django 3.1.2 on 2020-10-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_auto_20201010_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='gem',
        ),
    ]
