# Generated by Django 3.1.2 on 2020-10-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0019_remove_deals_gem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gems',
        ),
    ]
